### ISSUE TITLE
Migrate from Prometheus to Mimir

### ISSUE THREAD

**Issue by locmai** [locmai/humble#147]
- [x] Setup a minimal Mimir
- [x] Ensure the metrics flow into Mimir
- [x] Setup data sources with grafana.maibaloc.com
---
- ~Switch Prometheus to agent mode and clean up persistent storage~ move this to a new ticket

**Comment by locmai** [comment]
A bit of a tuning to have ingesters an distributors accept a heavy load of metrics:

```
        distributor:
          replicas: 2
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          extraArgs:
            'distributor.ingestion-rate-limit': "10000000"
            'distributor.ingestion-burst-size': "20000000"

        ingester:
          persistentVolume:
            size: 5Gi
          replicas: 3
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
          extraArgs:
            'ingester.max-global-series-per-user': "20000000"
```
